-- AlterTable
ALTER TABLE "employee" ADD COLUMN "lat" DOUBLE PRECISION;
ALTER TABLE "employee" ADD COLUMN "lng" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "work" ADD COLUMN "lat" DOUBLE PRECISION;
ALTER TABLE "work" ADD COLUMN "lng" DOUBLE PRECISION;
